import Head from "next/head";
import Image from "next/image";
import ExpandableButton from "@/components/expandable-button";
import socmed from "@/constants/socmed";
import aboutMe from "@/constants/about-me";
import clsx from "clsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-orange-600 w-full box-pixel h-screen">
        <div className="relative w-full bg-zinc-900 h-[650px] overflow-hidden dust">
          <div className="backlight digital"></div>
          <div className="absolute left-36 top-[100px] font-semibold p-8 bg-opacity-25 backdrop-blur-sm">
            <h1
              data-text="Kukuh Baiquni;"
              className="text-6xl font-rajdhani text-gray-700 name-effect"
            >
              Kukuh Baiquni;
            </h1>
            <p className="text-xl text-gray-400">Software Engineer & Data Analyst</p>
            <ul className="my-10 text-lg flex flex-col gap-y-2 text-orange-600 font-mono list-disc list-inside">
              <li>Web Development</li>
              <li>Mobile Apps Development</li>
              <li>Data Visualization</li>
            </ul>
            <div className="flex gap-2">
              {socmed.map((item, idx) => (
                <ExpandableButton
                  key={item.link}
                  index={idx}
                  text={item.text}
                  link={item.link}
                  color={item.color}
                  icon={<i className={item.icon}></i>}
                />
              ))}
            </div>
          </div>
          <Image
            src="/images/me.png"
            height={550}
            width={580}
            alt="me"
            className="absolute right-40 -top-10 animate-loop"
          />
        </div>
        <nav
          className={clsx(
            "h-[80px] backdrop-blur-sm bg-zinc-300 rotate-[2deg] w-[105%] relative -left-4 top-[-32px] mosaic",
            "border-t-8 border-orange-600",
          )}
        >
          <ul className="flex gap-40 text-zinc-900 text-opacity-100 justify-center items-center h-full anchor-nav text-xl font-semibold">
            <li>About Me</li>
            <li>Skills</li>
            <li>Expertises</li>
            <li>Experiences</li>
            <li>Portfolios</li>
          </ul>
        </nav>
      </main>
    </>
  );
}
